name: CI
on: 
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-lastest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build



